// Bilingual support. English is the default and lives at the site root; Thai
// lives under /th/. A lesson's language is encoded in its directory: Thai
// files live under `lessons/th/...`, so their content id starts with `th/`.
// (A directory prefix survives Astro's id slugification, where a `.th`
// filename suffix would not.) The "key" — the id with any `th/` prefix
// stripped — is shared across languages, so links and reading progress stay
// paired between the two editions.

import type { CollectionEntry } from 'astro:content';

export const LANGS = ['en', 'th'] as const;
export type Lang = (typeof LANGS)[number];
export const DEFAULT_LANG: Lang = 'en';

export function langFromId(id: string): Lang {
  return id.startsWith('th/') ? 'th' : 'en';
}

export function keyFromId(id: string): string {
  return id.replace(/^th\//, '');
}

export function lessonLang(entry: CollectionEntry<'lessons'>): Lang {
  return entry.data.lang;
}

/** Localized URL helpers — Thai paths get a /th prefix. */
export function homeHref(lang: Lang): string {
  return lang === 'en' ? '/' : '/th/';
}
export function lessonHref(lang: Lang, key: string): string {
  return lang === 'en' ? `/lessons/${key}/` : `/th/lessons/${key}/`;
}
export function trackHref(lang: Lang, id: string): string {
  return lang === 'en' ? `/tracks/${id}/` : `/th/tracks/${id}/`;
}
export function aboutHref(lang: Lang): string {
  return lang === 'en' ? '/about/' : '/th/about/';
}
export function searchHref(lang: Lang): string {
  return lang === 'en' ? '/search/' : '/th/search/';
}

/** "11 min" → Thai "11 นาที" for the read-time label. */
export function localizeDuration(duration: string, lang: Lang): string {
  return lang === 'th' ? duration.replace(/min/i, 'นาที') : duration;
}

interface Strings {
  navTracks: string;
  navAbout: string;
  navSearch: string;
  navDeck: string;
  navTheme: string;
  toOtherLang: string; // label of the link to the *other* language
  footerBlurb: string;
  footerColophon: string;
  heroTitle: string; // may contain <br> and <em>
  heroBody: string;
  continueLabel: string;
  badgeLive: string;
  badgeSoon: string;
  markRead: string;
  markedRead: string;
  readSuffix: string; // shown after the duration, e.g. "read"
  lessonOf: (n: number, total: number) => string;
  lessonsCount: (n: number) => string;
  pagerPrev: string;
  pagerNext: string;
  pagerTrack: string;
  pagerEnd: string;
  pagerBackHome: string;
  searchTitle: string;
  searchBlurb: string;
  searchUnavailable: string;
}

export const STR: Record<Lang, Strings> = {
  en: {
    navTracks: 'Tracks',
    navAbout: 'About',
    navSearch: 'Search',
    navDeck: 'Deck',
    navTheme: 'theme',
    toOtherLang: 'ไทย',
    footerBlurb: 'Front in the End — lessons in thinking like a frontend engineer.',
    footerColophon: 'Colophon',
    heroTitle: "Frameworks change.<br />The <em>reasons</em> don't.",
    heroBody:
      'Lessons for frontend engineers who can ship features but want the mental models — why rendering strategies exist, where state should live, what the network does to your UI. Plain HTML to heavily stateful apps, with working demos you can poke.',
    continueLabel: 'Continue where you left off',
    badgeLive: 'live',
    badgeSoon: 'coming soon',
    markRead: 'mark as read',
    markedRead: '✓ read',
    readSuffix: 'read',
    lessonOf: (n, total) => `lesson ${n} of ${total}`,
    lessonsCount: (n) => `${n} lessons`,
    pagerPrev: 'previous',
    pagerNext: 'next',
    pagerTrack: 'track',
    pagerEnd: 'end of track',
    pagerBackHome: 'Back to all tracks',
    searchTitle: 'Search',
    searchBlurb: 'Every lesson is indexed at build time — no server, no tracking, just Pagefind.',
    searchUnavailable:
      'Search index not found. It is generated by `npm run build` (Pagefind) and unavailable in dev mode.',
  },
  th: {
    navTracks: 'แทร็ก',
    navAbout: 'เกี่ยวกับ',
    navSearch: 'ค้นหา',
    navDeck: 'สไลด์',
    navTheme: 'ธีม',
    toOtherLang: 'EN',
    footerBlurb: 'Front in the End — บทเรียนว่าด้วยการคิดแบบ frontend engineer',
    footerColophon: 'เบื้องหลังเว็บนี้',
    heroTitle: 'Framework เปลี่ยนไปเรื่อย ๆ<br /><em>แต่เหตุผลเบื้องหลังไม่เปลี่ยน</em>',
    heroBody:
      'บทเรียนสำหรับ frontend engineer ที่ทำ feature ส่งได้อยู่แล้ว แต่อยากได้ mental model ข้างใต้ — ว่าทำไมแต่ละวิธี render ถึงมีอยู่ ว่า state ควรอยู่ที่ไหน ว่า network ทำอะไรกับ UI ของเราบ้าง ตั้งแต่ HTML ล้วน ๆ ไปจนถึง app ที่ state ซับซ้อน พร้อม demo ที่กดเล่นได้จริง',
    continueLabel: 'อ่านต่อจากที่ค้างไว้',
    badgeLive: 'พร้อมแล้ว',
    badgeSoon: 'เร็ว ๆ นี้',
    markRead: 'ทำเครื่องหมายว่าอ่านแล้ว',
    markedRead: '✓ อ่านแล้ว',
    readSuffix: 'อ่าน',
    lessonOf: (n, total) => `บทที่ ${n} จาก ${total}`,
    lessonsCount: (n) => `${n} บทเรียน`,
    pagerPrev: 'ก่อนหน้า',
    pagerNext: 'ถัดไป',
    pagerTrack: 'แทร็ก',
    pagerEnd: 'จบแทร็ก',
    pagerBackHome: 'กลับไปดูแทร็กทั้งหมด',
    searchTitle: 'ค้นหา',
    searchBlurb: 'ทุกบทเรียนถูก index ตอน build — ไม่มี server ไม่มี tracking มีแค่ Pagefind',
    searchUnavailable:
      'ไม่พบ search index — มันถูกสร้างตอน `npm run build` (Pagefind) จึงใช้ไม่ได้ในโหมด dev',
  },
};

/** The Thai read-time label puts the word first: "อ่าน 11 นาที" vs "11 min read". */
export function readLabel(duration: string, lang: Lang): string {
  return lang === 'th'
    ? `${STR.th.readSuffix} ${localizeDuration(duration, 'th')}`
    : `${duration} ${STR.en.readSuffix}`;
}
